<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestingSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>135d658a-684d-4d86-bdbd-8a1552982abc</testSuiteGuid>
   <testCaseLink>
      <guid>07efdb12-e808-481d-8d85-7c34bd5c6f0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/testingint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f01e431c-f62b-4a3b-90e9-881c4c117f6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8da8d913-5876-470d-ade3-bd03383ee069</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>734c5763-dace-4362-999b-11f72f6dab5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/testing</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d38fdc7a-f5b8-426d-90b7-a4da35005d01</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Testing</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d38fdc7a-f5b8-426d-90b7-a4da35005d01</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comment</value>
         <variableId>5f7173eb-6853-4ae9-8659-ca590586f9f3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
